export default {
  toggle: {
    text: 'left',
  },
  addDtlForm: {
    show: true,
    prodDev: '',
  },
  defaultForm: { // 신청폼 데이터
    ifNmKor: '',
    ifNmEng: '',
    mqfile: '',
    direction: '',
    async: '',
    msgPrc: '',
    recvPrg: '',
    fileTransType: '',
    sendDir: '',
    recvDir: '',
    recvCallShell: '',
    opCode: '',
    effect: '',
    recvList: [],
    sendList: [],
  },
  editForm: { // 신청폼 데이터
    ifNmKor: '',
    ifNmEng: '',
    mqfile: '',
    direction: '',
    async: '',
    msgPrc: '',
    recvPrg: '',
    fileTransType: '',
    sendDir: '',
    recvDir: '',
    recvCallShell: '',
    opCode: '',
    effect: '',
    recvList: [],
    sendList: [],
  },
  sendData: { // 송신
    company: '',
    sysNmKor: '',
    sysNmEng: '',
    hostNm: '',
    ipVip: '',
    ipNat: '',
    os: '',
    mid: 'MID',
    operator: '운영담당',
    manager: '담당매니저',
  },
  recvData: { // 수신
    company: '',
    sysNmKor: '',
    sysNmEng: '',
    hostNm: '',
    ipVip: '',
    ipNat: '',
    os: '',
    mid: 'MID',
    operator: '운영담당',
    manager: '담당매니저',
  },
  regList: [],
};
